version: '3.8'
services:
  # 1. Streamlit 앱 서비스 (기존)
  streamlit-app:
    build: .
    ports:
      - "80:8501" # 최종 사용자가 접속하는 포트 (OCI 80 -> Container 8501)
    container_name: streamlit-container
    restart: always
    # command: Streamlit 실행 명령어 (Dockerfile에 정의되어 있으면 생략 가능)

  # 2. Webhook 리시버 서비스 (새로 추가)
  webhook-receiver:
    build: .
    # command를 통해 Flask 앱을 5000번 포트에서 실행하도록 명시
    command: python webhook_receiver.py
    ports:
      - "5000:5000" # GitHub 웹훅이 접근하는 포트 (OCI 5000 -> Container 5000)
    container_name: webhook-container
    restart: always
    # Secret Key를 환경 변수로 전달 (보안을 위해 코드에 하드코딩하는 대신 이 방법을 권장)
    environment:
      - GITHUB_SECRET=web # <--- GitHub에 설정한 Secret Key로 변경!