version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: streamlit run app.py --server.port=8000 --server.enableCORS=false --server.enableXsrfProtection=false